### ISSUE TITLE
Color Point Cloud Support

### ISSUE THREAD

**Issue by braca51e** [luxonis/depthai-ros#104]
Is there anyway to get a color point cloud, currently just overlaying the right camera frame gives a monochrome cloud, so why is there no demo for color point cloud?

Thanks

**Comment by Luxonis-Brandon** [comment]
Yes there is a way but I'm not technical enough to share.  @OanaMariaVatavu I think can share but might need help from @daxoft on the ROS side.

**Comment by saching13** [comment]
Hello @braca51e ,
      You can see RGB pointCloud by running `roslaunch depthai_examples stereo_inertial_node.launch`
 

![image](https://user-images.githubusercontent.com/43363595/165430673-8f94aca4-aee5-49a6-b311-1281c3dfe01a.png)

**Comment by braca51e** [comment]
@saching13 @Luxonis-Brandon Thanks for your answers will test!

**Comment by braca51e** [comment]
@saching13 I've tested it and it works but after some frames it freezes out! Are you experiencing the same problem?

**Comment by saching13** [comment]
ran it for 10min. don't see an issue. do you get any error ? can I know which host and ROS version?

**Comment by braca51e** [comment]
no errors I'm using noetic

**Comment by saching13** [comment]
Hhmm. Same here. 
Which OAK version ?

**Comment by braca51e** [comment]
OAK-D no poe

**Comment by braca51e** [comment]
For some reason it stops publishing the points after a few seconds

**Comment by saching13** [comment]
WIll check on OAK-D-Poe and get back on this

**Comment by saching13** [comment]
Ah got it. queue size of depthai or of pointcloud nodelet ?
