### ISSUE TITLE
POE bandwidth 

### ISSUE THREAD

**Issue by k-gupta** [luxonis/depthai-ros#109]
Is there a document which documents the bandwidth utilization for the cameras on the wire? Trying to estimate how many cameras we can plug in before we saturate the link. 

Looking at both Poe and USB variants for the oak-d depth pro.

**Comment by saching13** [comment]
Here is the latency information for each resolution and camera. 

@Erol444  if you have more details can you share ?

**Comment by k-gupta** [comment]
> 

Looks like the link might be missing.

**Comment by Serafadam** [comment]
Documentation link [available here](https://docs.luxonis.com/projects/api/en/latest/tutorials/low-latency/).
