### ISSUE TITLE
Ros on RPi

### ISSUE THREAD

**Issue by shruty808** [luxonis/depthai-ros#114]
Hello , 
I have connected Oak -D Lite to rpi4 usb . my raspberry pi has ros ubuntu image and ros-noetic in it . I am getting cmake error when i follow the procedure mentioned . Can someone help !

**Comment by saching13** [comment]
@daxoft  can you take this one

**Comment by daxoft** [comment]
Hi @shruty808 can you show us the cmake error you are getting?

**Comment by saching13** [comment]
Deb packages released for RPI too. So closing this in lieu of that.
