### ISSUE TITLE
catkin_make error

### ISSUE THREAD

**Issue by dolf321** [luxonis/depthai-ros#118]
Hello, when running the ```catkin_make --cmake-args -D'depthai_DIR=/home/rami/nr22-software/include/depthai-core/build -fPIC'``` command and building the catkin library  i get this error: 

I know that the library is already set statically so why is this error still appearing i even tried forcing the fPIC parameter but to no avail. 

![image](https://user-images.githubusercontent.com/65448126/171805578-0020d76b-6ac1-40fe-a58d-932c597a6de4.png)

**Comment by saching13** [comment]
can you clear the `.hunter` folder in your `home` and rebuild it ?

**Comment by dolf321** [comment]
Yes that fixed the issue! Thank you
