### ISSUE TITLE
ubuntu22.04 dependency problem

### ISSUE THREAD

**Issue by MarcoGaller** [luxonis/depthai-ros#124]
https://raw.githubusercontent.com/luxonis/depthai-docs-website/master/source/_static/install_dependencies.sh
I found that when this script was executed on ubuntu22.04, some dependencies were replaced by other dependencies in 22.04. Can you improve this dependency script so that it can be used on ubuntu22.04

**Comment by saching13** [comment]
Ah yes. It has been low-hanging fruit. Will do

**Comment by saching13** [comment]
I updated the dependencies to bare min needed to run the `depthai-ros`.
