### ISSUE TITLE
oak-d pro DotProjector and floodLightmA is not running

### ISSUE THREAD

**Issue by youngjae41** [luxonis/depthai-ros#132]
I have oak-D-Pro and oak-D-PRO POE version 

I used stereo_inertial_node.launch 

   arg name="enableDotProjector"    default="true"
   arg name="enableFloodLight"      default="true"
   arg name="dotProjectormA"        default="800.0" or default="200.0"
   arg name="floodLightmA"          default="200.0"

DotProjector and floodLightmA is not running

In depthai_demo.py it works fine

**Comment by saching13** [comment]
it is running increase the values. Make it `1000` for example

**Comment by youngjae41** [comment]
@saching13 thanks

How is the maximum ?

**Comment by saching13** [comment]
> @saching13 thanks
> 
> 
> 
> How is the maximum ?

I didn't get you.

**Comment by youngjae41** [comment]
@saching13 setting it to 1000 doesn't work

**Comment by saching13** [comment]
Ok. let me check and get back

**Comment by youngjae41** [comment]
Thanks @saching13 

and there is a difference of about 7 FPS in POE type and USB type

**Comment by saching13** [comment]
@youngjae41  check [this](https://github.com/luxonis/depthai-ros/issues/85) please

**Comment by saching13** [comment]
and can you record a video of your floodLight and share it with us ?

**Comment by saching13** [comment]
### With FloodLight

![image](https://user-images.githubusercontent.com/43363595/188698046-1c8eee6f-43b5-4c22-9563-d75146bde83b.png)

### Without FloodLight
![image](https://user-images.githubusercontent.com/43363595/188698070-0bfc3230-643f-492a-b984-c16771a6cd86.png)

**Comment by saching13** [comment]
### With Floodlight and DotProjector. 

![image](https://user-images.githubusercontent.com/43363595/188698355-e089ccbc-c40f-4ab5-b07f-9a617fa11929.png)

**Comment by saching13** [comment]
Sorry for the issue. We changed the boardNames internally in the new batches of manufacturing. And this new check was not added here. I fixed and updated the code. it should work now. @youngjae41

**Comment by youngjae41** [comment]
@saching13 Thanks 

work now!!
