### ISSUE TITLE
[Feature request] OV9782 support

### ISSUE THREAD

**Issue by Erol444** [luxonis/depthai-ros#134]
Add a branch of the `depthai-ros `that points to `depthai-core`'s branch `multi_cam_support` where OV9782 is supported.

**Comment by Erol444** [comment]
I believe this should already be supported now that multi_cam_support was merged?

**Comment by Serafadam** [comment]
I'll close that when there'll be an example of use :slightly_smiling_face:

**Comment by Serafadam** [comment]
Closing with https://github.com/luxonis/depthai-ros/pull/191
