### ISSUE TITLE
Create visuailzation_msg for ROS2 spatial detection

### ISSUE THREAD

**Issue by Tanjim13** [luxonis/depthai-ros#140]
Hi, I am using turtlebot4. It is not publishing the topics and cannot see the bounding box in rviz2. All other launch files in depthai_examples is working. But yolov4 is not working properly. Should I need to include any dependencies? Cause it is not showing any errors. Or is there any instruction that I should follow?

**Comment by saching13** [comment]
We have not written a plugin for visualization. Try subscribing from command line to cross check.

**Comment by Tanjim13** [comment]
@saching13 , I have used ros2 topic echo  /color/yolo4_Spatial_detection and findout this (look at the yolov4.txt). But the problem is is_tracking: false all the time. If you have not written a plugin for visualization, that means I cannot see the bounding box? right? Also I can  visualize "stereo/depth" and "color/image" topics from rviz2 but without a bounding box. And color/yolov4_Spatial_detections is not visible(this is the topic with bounding box and detection, right). 
[yolov4.txt](https://github.com/luxonis/depthai-ros/files/9612499/yolov4.txt)

**Comment by Tanjim13** [comment]
Today, I have run yolov4, it is not publishing any topics. I am not sure what is the reason. Other scripts in depthai_examples are working properly. But this script is causing the problem. Even I tried to subscribe from the terminal. When I echo topics of this script it is not showing me any data on the terminal. I have tried to echo "/color/yolov4_Spatial_detections, /color/image, /stereo/depth" topics which should be published according to the script. Even I do not see any errors.
![Screenshot 2022-09-21 at 12 32 54 PM](https://user-images.githubusercontent.com/18646128/191561033-f0272040-d955-4667-a556-384527413e78.png)

**Comment by saching13** [comment]
@Tanjim13  I have the marker publishing for ROS1 [here](https://github.com/luxonis/depthai-ros/tree/ros-release/depthai_examples/ros1_scripts).

Currently we are swamped. Will add one to ROS2 soon. 
If you write one in the meantime. Feel free to create a PR.

**Comment by Serafadam** [comment]
Added in https://github.com/luxonis/depthai-ros/pull/336

**Comment by jiangwenjie1011** [comment]
I found it was because the current provided by the raspberry pie usb interface is too small, I removed the radar usb interface, it works normally now
