### ISSUE TITLE
[BUG] catkin_make build issues with HASH mismatch

### ISSUE THREAD

**Issue by an99990** [luxonis/depthai-ros#141]
**Describe the bug**

`-- +++ processing catkin package: 'depthai_examples'
-- ==> add_subdirectory(depthai-ros/depthai_examples)
CMake Error at depthai-ros/depthai_examples/CMakeLists.txt:25 (file):
  file DOWNLOAD HASH mismatch
    for file: [/home/ubuntu/dai_ws/src/depthai-ros/depthai_examples/resources/mobilenet-ssd_openvino_2021.2_6shave.blob]
      expected hash: [f0e14978b3f77a4f93b9f969cd39e58bb7aef490]
        actual hash: [9eab384252b108394f886d5ed0b0b9ab48391c6b]
             status: [28;"Timeout was reached"]
CMake Error at depthai-ros/depthai_examples/CMakeLists.txt:32 (file):
  file DOWNLOAD HASH mismatch
    for file: [/home/ubuntu/dai_ws/src/depthai-ros/depthai_examples/resources/yolov4_tiny_coco_416x416_openvino_2021.4_6shave_bgr.blob]
      expected hash: [219d949610a5760e62a8458941e1300b81c3fe4a]
        actual hash: [9ce38aab5b362a9a146d86f96cf91f7243bc3a69]
             status: [28;"Timeout was reached"]
-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/dai_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/ubuntu/dai_ws/build/CMakeFiles/CMakeError.log".`

**Minimal Reproducible Example**
Reproduced installation from source step from README

**Expected behavior**
successful build

**Comment by saching13** [comment]
@an99990  it is a your network issue at that time. clear your builds and files and redo it.
