### ISSUE TITLE
[BUG] stereo image topic corrupted

### ISSUE THREAD

**Issue by an99990** [luxonis/depthai-ros#144]
**Check if issue already exists**

topic stereo image is weird, see below screenshot for more details.

**Describe the bug**
I wanted to visualize the topic stereo/image but theres nothing to see.

**Minimal Reproducible Example**
roslaunch depthai_examples stereo_inertial_publisher.launch

**Screenshots**
![stere_issue](https://user-images.githubusercontent.com/87030365/193102623-936eeeba-cd1f-46af-9e04-b96754396b70.png)

**Pipeline Graph**

**Attach system log**
 - Provide output of [log_system_information.py](https://github.com/luxonis/depthai/blob/main/log_system_information.py)
 - Which OS/OS version are you using? Linux
 - Which ROS version are you using?  ROS1 Melodic

**Additional context**

**Comment by saching13** [comment]
@an99990  I don't see anything corrupted above.

**Comment by saching13** [comment]
If your issue is same as #147  
Please follow there. And close this as duplicate.

**Comment by Huynh-Anh** [comment]
no its not the same topic. The black Image is the stereo topic and the clear image is another topic

![image](https://user-images.githubusercontent.com/35234402/193709649-4afe69cf-859e-41f4-a6ed-fed77f638d76.png)

whats the difference between the topic `/stereo_inertial_publisher/stereo/image` and `/stereo_inertial_publisher/stereo/depth` ?

If i want to calculate the centroids using the depth information which topic should i use ?
thank you

**Comment by akshat-v** [comment]
Also facing the same issue.

**Comment by saching13** [comment]
One is in millimeter and the other is in meters.

[This](https://github.com/luxonis/depthai-ros/blob/9ac79711a7ae247588a86c75911ddb306e03617f/depthai_examples/launch/stereo_inertial_node.launch#L120-L125) nodelet takes the `/stereo_inertial_publisher/stereo/depth` which is in `mm`  and converts it to `/stereo_inertial_publisher/stereo/image` which is in meters
