### ISSUE TITLE
[QUESTION] {Differences between nodes}

### ISSUE THREAD

**Issue by Huynh-Anh** [luxonis/depthai-ros#148]
I would like to know the difference between the launch files.

For example stereo_inertial_publisher, stereo_node vs stereo_nodelet ?
Do they have different purposes ?

**Comment by saching13** [comment]
stereo_node and nodelet was just a demo of how to build them using node and nodelet. 
More work is done on stereo_inertial_node which has more control and parameters in the launch file to adjust the RGBD, object detection, resolution, exposure control etc..

**Comment by an99990** [comment]
thank you @saching13  
whats the difference between the color/image topic and the usual left/image topic between the nodes ?

**Comment by saching13** [comment]
Color/image is from the center camera

**Comment by Serafadam** [comment]
Seems to be answered so closing, if you think this should remain open, please tag me in a comment here.
