### ISSUE TITLE
Change the point cloud display orientation

### ISSUE THREAD

**Issue by yo4hi6o** [luxonis/depthai-ros#15]
Hi!

I was able to display the point cloud with rviz with'roslaunch depthai_examples stereo_nodelet.launch'.

The orientation of the point cloud display displayed in rviz is landscape by default, but I would like to change the orientation of the point cloud display from top to bottom. Where can I adjust it?

Thanks!

**Comment by saching13** [comment]
it is displayed based on where the map origin is set on rviz. I have set it to the base of the URDF file of OAK-D in the example.

Can I know why you would want to change that and the use case of changing in the visualization?

**Comment by yo4hi6o** [comment]
Thank you saching13!
The purpose is to display the position of the picking object by the manipulator as a point cloud by the oak-d camera.
The position of the camera is fixed from above.

**Comment by saching13** [comment]
And do you have a TF link from the Manipulator to the OAK-D's state publisher baselink ?

**Comment by yo4hi6o** [comment]
> And do you have a TF link from the Manipulator to the OAK-D's state publisher baselink ?
