### ISSUE TITLE
[Feature-Request] {ROS2 example with multiple Oak-D pro cameras}

### ISSUE THREAD

**Issue by s183898** [luxonis/depthai-ros#169]
### why:
I am looking into using multiple Oak-D Pro's in ROS2 on a Jetson Xavier NX.

### what:
Example code that allows the user to choose which Oak camera to open and enables multiple Oak's to be running with ROS2 at the same time.

**Comment by Serafadam** [comment]
Hi! Thanks for the interest, currently [there is a PR](https://github.com/luxonis/depthai-ros/pull/153/files) which might be a  good starting point for now, we will also provide more examples in the near future.

**Comment by s183898** [comment]
Cool, thanks a lot. Looking forward to examples as well :)
