### ISSUE TITLE
Feature request: Enable/disable camera through ROS2 service

### ISSUE THREAD

**Issue by saching13** [luxonis/depthai-ros#170]
It would be useful to be able to enable/disable the camera streams at runtime or put the camera into a low power state when not in use, without actually killing the ROS2 node. This could be done with a [SetBool](http://docs.ros.org/en/api/std_srvs/html/srv/SetBool.html) service.
Moving from [here](https://github.com/luxonis/depthai-ros-examples/issues/59)

**Comment by saching13** [comment]
Instead of setbool. How about using a lifecycle node ?

**Comment by Serafadam** [comment]
I'd say lifecycle nodes are on the list, but until [this clears out](https://github.com/ros-perception/image_common/issues/108) we can add a service

**Comment by silviazpi** [comment]
Why did you close it? Is it already added?

**Comment by Serafadam** [comment]
Hi, yes, camera start/shutdown services have been available for some time now
