### ISSUE TITLE
[BUG] {Attempted to start Color camera - NOT detected!}

### ISSUE THREAD

**Issue by roni-kreinin** [luxonis/depthai-ros#174]
**Describe the bug**
Camera is not detected when launching ROS2 nodes

**Attach system log**
 - Which OS/OS version are you using?
 Ubuntu 20.04 Server on RPi4
 - Which ROS version are you using?
Galactic

**Additional context**
See https://github.com/turtlebot/turtlebot4/issues/80

**Comment by Serafadam** [comment]
Original issue is closed, closing here as well
