### ISSUE TITLE
[Feature-Request] {WLS filter examples for ROS2}

### ISSUE THREAD

**Issue by s183898** [luxonis/depthai-ros#175]
### why and what:
The existing ROS2 examples with depth topc is very noisy, when visualized in rviz, however in one of your experiments:
https://github.com/luxonis/depthai-experiments/tree/master/gen2-wls-filter
a wls filter is implemented which gives very nice results. It would save us a lot of time to have an example working with wls filtering in ROS2 as well. Generally speaking more ROS2 examples would be appreciated.

**Comment by Serafadam** [comment]
Example added in https://github.com/luxonis/depthai-ros/pull/247
