### ISSUE TITLE
[Feature-Request] Optionally do not publish in a "lazy" fashion in the BridgePublisher

### ISSUE THREAD

**Issue by vinnnyr** [luxonis/depthai-ros#189]
### Start with the `why`:
We have had a few issues with the BridgePublisher, that we have pinned down to issues / gaps between  when the publisher has been advertised and when the subscriber has been counted. 

To define the term, Lazy publishers are those which only publish when non-zero subscribers have been counted.

In our case, the lazy publisher does not really provide any meaningful advantage. 

### Move to the `what`:
In the BridgePublisher, I suggest adding a "non lazy" publisher that the user can opt-in to using.

https://github.com/luxonis/depthai-ros/blob/165bbc9fe84ec6f836e959f630eb6fc023803141/depthai_bridge/include/depthai_bridge/BridgePublisher.hpp#L211

### Move to the `how`:
1. add an optional bool value to control the laziness on construction, with default True
2. edit the PublishHelper to take this bool into account when attempting to count subscribers, etc.

**Comment by Serafadam** [comment]
Added in https://github.com/luxonis/depthai-ros/pull/381
