### ISSUE TITLE
[Feature-Request] {Allow for specifying of device info in examples}

### ISSUE THREAD

**Issue by vinnnyr** [luxonis/depthai-ros#190]
### Start with the `why`:
I want to be able to run the examples, such as the `stereo_publisher` example on a system that may have multiple depthai boards connected. Specifically, multiple PoE OAK-D W.
https://github.com/luxonis/depthai-ros/blob/humble/depthai_examples/src/stereo_publisher.cpp

### Move to the `what`:
For all examples, I would like to be able to specify an IP, MXID, and Xlink Protocol optionally. 

### Move to the `how`:
Have ROS parameters for IP / The DeviceInfo string that gets passed to the constructer of `dai::Device`

**Comment by Serafadam** [comment]
Hi, if you are using Humble then I can suggest using `depthai_ros_driver`, there is an example of multicamera setup there. If there are any problems with setting multiple PoE examples please let me know.
 https://github.com/luxonis/depthai-ros/blob/humble/depthai_ros_driver/launch/example_multicam.launch.py
 (here is an example params file with mxids specified https://github.com/luxonis/depthai-ros/blob/humble/depthai_ros_driver/config/multicam_example.yaml, same goes for IP)

**Comment by Serafadam** [comment]
Closing as completed since the functionality is available in `depthai_ros_driver`
