### ISSUE TITLE
ros noetic stereo_inertial_node and depthai_ros_driver/pointcloud.launch error

### ISSUE THREAD

**Issue by youngjae41** [luxonis/depthai-ros#210]
Jetson orin AGX + Oak-D-PRO 

depthai_ros_driver/pointcloud.launch error

![Screenshot from 2023-01-20 14-16-42](https://user-images.githubusercontent.com/55374072/213623027-1cabf388-5342-4d31-b4d8-11f483f86d60.png)

stereo_inertial_node launch error

![Screenshot from 2023-01-20 14-21-25](https://user-images.githubusercontent.com/55374072/213623151-b9f2c154-9a6c-4658-8f05-fc86de643b42.png)

**Comment by Serafadam** [comment]
Hi, `pointcloud.launch` should be fixed by https://github.com/luxonis/depthai-ros/pull/211, as for the `stereo_intertial_node`, can you try adding `export OPENBLAS_CORETYPE=ARMV8` to your `bashrc` file?

**Comment by youngjae41** [comment]
@Serafadam Thanks !! works well

**Comment by youngjae41** [comment]
@Serafadam  Hello Serafadam

![Screenshot from 2023-01-25 11-24-54](https://user-images.githubusercontent.com/55374072/214466764-163b3ac5-e8c0-4211-a4f8-75c02d7e505b.png)


desktop works well 
but jetson not work!

stereo_node.launch file works well 
but stereo_inertial_node.launch not wokr

Jetpack 5.0.2 
ros Noetic 
opencv libopencv 4.2 or opencv 4.5.1

**Comment by youngjae41** [comment]
@Serafadam

I'm found problem

it was cv_brige issue


changed

/opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake 
change this line:

set(_include_dirs "include;;/usr/include/opencv4") 
to

set(_include_dirs "include;/usr/local/include/opencv4")
