### ISSUE TITLE
depthai_ros_driver Humble release

### ISSUE THREAD

**Issue by doisyg** [luxonis/depthai-ros#215]
### Start with the `why`:
For convenience and for ROS users not to have to deal with building it from source

### Move to the `what`:
Releasing built binaries of `depthai_ros_driver` to current ROS2 LTS, i.e. Humble

### Move to the `how`:
Same as for the other packages

Any plans ? Anything blocking ?

**Comment by ladrians** [comment]
+1 to the request, for ROS1 Noetic would be great too, using a rpi4 it takes a lot of time on every compile cycle.

**Comment by saching13** [comment]
we released it last week.
[here](https://github.com/ros/rosdistro/pull/35978#event-8391358227) is the PR for Humble release.
[here](https://github.com/ros/rosdistro/pull/35979#event-8401517187) for the Noetic release

**Comment by Serafadam** [comment]
We also have Docker images that you can check out, just run 
`docker run -it -v /dev/:/dev/  --privileged --network host -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix luxonis/depthai-ros:humble-latest`

**Comment by roni-kreinin** [comment]
@saching13 @Serafadam The package is failing to build on the buildfarm https://build.ros2.org/job/Hbin_ujv8_uJv8__depthai_ros_driver__ubuntu_jammy_arm64__binary/

**Comment by saching13** [comment]
Yes. I noticed it yesterday. Sent a PR to enable pr testing on it. 
Will have new version up in 2 days.
Sorry for the issue.

**Comment by doisyg** [comment]
@saching13 any updates ? (sorry for pushing but it is quite heavy to build from src, @scheunemann)

**Comment by saching13** [comment]
Sorry for the delay. @doisyg 
PR testing is still not working for some reason. I have requested Tully to see what is the issue. 
That said I sent out a release PR either way [here](https://github.com/ros/rosdistro/pull/36058). Hoping to be merged today.

**Comment by saching13** [comment]
@doisyg  @roni-kreinin  release is up and looks like it's stable.
https://build.ros2.org/job/Hbin_ujv8_uJv8__depthai_ros_driver__ubuntu_jammy_arm64__binary/

**Comment by Serafadam** [comment]
Packages are available for Humble, closing issue.
