### ISSUE TITLE
[Feature-Request] Move stl files to separate description package

### ISSUE THREAD

**Issue by Aposhian** [luxonis/depthai-ros#236]
### Start with the `why`:
stl files take up a lot of space (~60MiB)

### Move to the `what`:
create new package: `depthai_description` that holds urdf and stl files

**Comment by Serafadam** [comment]
Hi, I agree with putting those files in another package for clarity, but size of the package will remain the same in that case (unless I'm missing something)

**Comment by Aposhian** [comment]
You don't need the URDF of the oak-d's in order to make use of features like the bridge publisher, so if you break it out and make `depthai_bridge` not depend on `depthai_description` then you can install `depthai_bridge` but not necessarily `depthai_description`. Then that decreases your total install load.

**Comment by Serafadam** [comment]
Makes sense :+1:

**Comment by Serafadam** [comment]
Added in https://github.com/luxonis/depthai-ros/pull/256
