### ISSUE TITLE
[BUG] {start_camera service kills the node if called while camera is already running}

### ISSUE THREAD

**Issue by roni-kreinin** [luxonis/depthai-ros#238]
**Describe the bug**

Calling the `start_camera` service when the camera is already running will cause the node to die.

**Minimal Reproducible Example**
Launch the camera node and call:

```bash
ros2 service call /oakd/start_camera std_srvs/srv/Trigger {}
```
Result:
```
[component_container-6] terminate called after throwing an instance of 'std::runtime_error'
[component_container-6]   what():  Pipeline is already running
[ERROR] [component_container-6]: process has died [pid 4789, exit code -6, cmd '/opt/ros/humble/lib/rclcpp_components/component_container --ros-args -r __node:=oakd_container -r __ns:=/'].
```
**Expected behavior**
Nothing should happen since the camera is already running

**Screenshots**

**Pipeline Graph**

Please also provide a screenshot of your pipeline using the [DepthAI Pipeline Graph](https://github.com/geaxgx/depthai_pipeline_graph).

**Attach system log**
Ubuntu 22.04 Server
ROS2 Humble
Raspberry Pi 4B
depthai_ros_driver v2.6.3

**Comment by Serafadam** [comment]
Fixed in https://github.com/luxonis/depthai-ros/pull/241
