### ISSUE TITLE
IMU topic

### ISSUE THREAD

**Issue by stevemartinov** [luxonis/depthai-ros#25]
Hi,

It says that OAK-D includes the IMU:
`This DepthAI variant includes three onboard cameras and the BNO085 IMU and interfaces over USB3C to the host, allowing use with your (embedded) host platform of choice, including the Raspberry Pi and other popular embedded hosts. `

How can I get this IMU data over the ROS topic?

**Comment by saching13** [comment]
IMU data messages are not added yet. I am planning to work on that next week.

**Comment by Luxonis-Brandon** [comment]
Oh and FWIW @stevemartinov here is the IMU API in C++/Python:
https://docs.luxonis.com/projects/api/en/latest/components/nodes/imu/
Just to give a heads up on what is there in the meantime.
