### ISSUE TITLE
[BUG] {Param 'nnName' in stereo_inertial_node.launch wasn't passed to the node.}

### ISSUE THREAD

**Issue by RangerOnMars** [luxonis/depthai-ros#254]
I tried to change 'nnName' param in 'stereo_inertial_node.launch' to deploy my custom NN model on OAK and nothing happened.
I tried to fix this issue and found that 'nnName' in 'stereo_inertial_node.launch' wasn't passed to the node,and the parameter 'nnName' is also not declared in stereo_inertial_publisher.cpp.I created a PR and fixed this issue #253

**Comment by Serafadam** [comment]
PR merged, closing the issue, thanks for the fix!
