### ISSUE TITLE
ROS Noetic Modular Camera Support

### ISSUE THREAD

**Issue by Willis-Aero** [luxonis/depthai-ros#255]
Hello,

I was searching through the DepthAI ROS Noetic example code, and noticed the camera model was specified as Oak-D. Is there support for modular cameras such as OAK-FFP-3P in ROS Noetic? Thank you for the assistance.

Example code line 4:
https://github.com/luxonis/depthai-ros/blob/noetic/depthai_examples/launch/yolov4_publisher.launch

**Comment by Serafadam** [comment]
Hi,
`depthai_examples` is more a demonstration of example use cases and how to set up custom camera configuration streaming using classes from `depthai_bridge`, there's no example for setting up modular camera unfortunately, but it's pretty straightfoward to do that.

In case of depthai_ros_driver, you can use [CamArray](https://github.com/luxonis/depthai-ros#stoppingstarting-camera-for-power-savingreconfiguration) pipeline configuration option that outputs streams from all available sensors, though currently it's not yet possible to setup custom NN/Depth nodes in this option (you could easily modify source code [here](https://github.com/luxonis/depthai-ros/blob/noetic/depthai_ros_driver/src/pipeline_generator.cpp) to add that option.
