### ISSUE TITLE
Vast Performance difference between amd64 and arm64 containers

### ISSUE THREAD

**Issue by dlefkaditis** [luxonis/depthai-ros#272]
Hello all!

I am not a ROS expert so let me know if you need more information than what I provide...

I have been having some issues with running the arm64 ROS2 containers on a Jetson Xavier NX (same on a Jetson Nano). Running `ros2 launch depthai_examples stereo_inertial_node.launch.py` launches rviz with no visible camera images, no pointcloud visualisation and no mapping. Rviz reports that image_raw and pointcloud messages are recieved. It also reports only 2fps. The cpu useage is ~50%, which I interprete as computational resources are not the issue here. Please see screenshot below:
![Screenshot from 2023-04-04 16-53-41](https://user-images.githubusercontent.com/36536777/229847755-2c2ec9b4-8798-462f-9ef8-6438dca4aeb3.png)

If I run the same thing on my laptop, it appears fine with 31fps:
![Screenshot from 2023-04-04 16-50-43](https://user-images.githubusercontent.com/36536777/229848397-73b3acc0-6d8c-4484-ab17-40cdf7029311.png)

This is on the latest humble release (2.7.0). In the previous releases things were even worse as rviz was not receiving pointcloud messages even if they were present (but low frequency) using `ros2 topic hz /oak/points`. 

Looking forward to your responses...

**Comment by Erol444** [comment]
Let's continue conversation at https://discuss.luxonis.com/d/1284-vast-performance-difference-between-amd64-and-arm64-docker-containers
