### ISSUE TITLE
[BUG] {[ROS] stop_camera service crashes camera node}

### ISSUE THREAD

**Issue by AlexTiniakov** [luxonis/depthai-ros#294]
I use ros noetic package installed from apt install. Run camera node with command:
`roslaunch depthai_ros_driver camera.launch`
Then I try to stop camera using service stop_camera:
`rosservice call /oak/stop_camera "{}"`
This call returns error:
`ERROR: transport error completing service call: unable to receive data from sender, check sender's logs for details`
And node crashes with error:
```
[ INFO] [1682334837.020916428]: Stopping camera!
[oak_nodelet_manager-2] process has died [pid 74600, exit code -11, cmd /opt/ros/noetic/lib/nodelet/nodelet manager /nodelet_manager/load_nodelet:=oak/nodelet_manager/load_nodelet /nodelet_manager/unload_nodelet:=oak/nodelet_manager/unload_nodelet /nodelet_manager/list:=oak/nodelet_manager/list __name:=oak_nodelet_manager __log:=/home/deusrobots/.ros/log/5465699c-e282-11ed-808d-a7219deb1dcb/oak_nodelet_manager-2.log].
log file: /home/deusrobots/.ros/log/5465699c-e282-11ed-808d-a7219deb1dcb/oak_nodelet_manager-2*.log
[ INFO] [1682334840.695123739]: Bond broken, exiting
================================================================================REQUIRED process [oak-3] has died!
process has finished cleanly
log file: /home/deusrobots/.ros/log/5465699c-e282-11ed-808d-a7219deb1dcb/oak-3*.log
Initiating shutdown!
================================================================================
[oak-3] killing on exit
[oak_state_publisher-1] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

```
![Screenshot from 2023-04-24 14-18-08](https://user-images.githubusercontent.com/39567406/233981502-4997d0da-8caf-4e86-afa2-3f197d1d7cbe.png)
![Screenshot from 2023-04-24 14-18-19](https://user-images.githubusercontent.com/39567406/233981525-64c8c9a9-4040-446d-90e9-37f7af85606d.png)

**Comment by Serafadam** [comment]
Hi, this should be fixed in latest Noetic release, you can check it out using Docker/building from source before official release on apt.

**Comment by Serafadam** [comment]
Closing the issue as it's resolved, please feel free to reopen it if you still experience issues.
