### ISSUE TITLE
[Feature-Request] Custom output image size for Noetic branch

### ISSUE THREAD

**Issue by lasuomela** [luxonis/depthai-ros#295]
Hello, thanks for the nice work.

Are you planning to implement the custom output image size feature for ROS Noetic? I can see that it is already available in the Humble branch **(https://github.com/luxonis/depthai-ros/commit/571c354b092d26d0adce89c58b58ed8acc661aa8)**. If yes, what is the timeline?

Br,
Lauri

**Comment by Serafadam** [comment]
Hi, this change is included in https://github.com/luxonis/depthai-ros/pull/275, which will hopefully be merged & released today.

**Comment by lasuomela** [comment]
Allright, thanks for the information!
