### ISSUE TITLE
[BUG] {Unable to build ros driver for FFC-4p}

### ISSUE THREAD

**Issue by Peize-Liu** [luxonis/depthai-ros#296]
My PC is running Ubuntu20.04 using Ros Noetic. I followed the instrcution in readme, everything went right when come into `catkin_make_isolated` 
![image](https://user-images.githubusercontent.com/54743766/234060349-013022cb-b707-4e72-89c3-d194867f21e0.png)
the same problem on my Orin NX
![image](https://user-images.githubusercontent.com/54743766/234060547-31ec902d-0513-4f87-8997-61206264443d.png)

**Comment by Serafadam** [comment]
Hi, could you check what branch are you on?

**Comment by Peize-Liu** [comment]
I am stupid, I did not change to noetic branch.
