### ISSUE TITLE
[BUG] Build failure on ROS2 Humble with depthai-core V2.19.1

### ISSUE THREAD

**Issue by hardesh-peppermint** [luxonis/depthai-ros#297]
**Describe the bug**

Hi, I'm getting build failture with the following error:
```
/home/harshal/depthai_ws/src/depthai-ros/depthai_ros_driver/src/param_handlers/sensor_param_handler.cpp: In member function ‘void depthai_ros_driver::param_handlers::SensorParamHandler::declareParams(std::shared_ptr<dai::node::ColorCamera>, dai::CameraBoardSocket, depthai_ros_driver::dai_nodes::sensor_helpers::ImageSensor, bool)’:
/home/harshal/depthai_ws/src/depthai-ros/depthai_ros_driver/src/param_handlers/sensor_param_handler.cpp:71:85: error: ‘THE_1440X1080’ is not a member of ‘dai::ColorCameraProperties::SensorResolution’
   71 |                         {"1440X1080", dai::ColorCameraProperties::SensorResolution::THE_1440X1080}};

```

I'm using the humble branch of depthai-ros with v2.19.1 of depthai-core 

The corresponding submodule depthai-share of depthai-core seems to have that resolution at https://github.com/luxonis/depthai-shared/blob/aa3e0564c0de3ef66cb6b240ff2b65ed3ed70aba/include/depthai-shared/properties/ColorCameraProperties.hpp#L55

**Comment by Serafadam** [comment]
Hi, can you update your depthai-core? Latest released version is v2.20.2

**Comment by hardesh-peppermint** [comment]
I was actually facing some issues with v2.20.2 last week. Is it working alright for you? 

I wasn't getting any streams from the camera

**Comment by Serafadam** [comment]
It should be working fine, could you post logs that you had with v2.20.2?

**Comment by manikjslb** [comment]
I built the package with galactic by just getting rid of THE_1440X1080 related lines of code from 
[depthai_ros_driver/src/dai_nodes/sensors/sensor_helpers.cpp](https://github.com/luxonis/depthai-ros/blob/786288ebcdd188cc2f880ff7d53fc620cd2df637/depthai_ros_driver/src/dai_nodes/sensors/sensor_helpers.cpp)

and 

[depthai_ros_driver/src/param_handlers/sensor_param_handler.cpp](https://github.com/luxonis/depthai-ros/blob/786288ebcdd188cc2f880ff7d53fc620cd2df637/depthai_ros_driver/src/param_handlers/sensor_param_handler.cpp)

**Comment by hardesh-peppermint** [comment]
Closing this as the driver is working with V2.20.2.

@Serafadam, Can you also start mentioning the version of depthai-core that supports the particular version of depthai-ros-driver? If it's already there then please point me to the right document

**Comment by Serafadam** [comment]
Hi, thanks for the information, as for depthai-core versioning, the main version that we target is the latest one available on APT.
