### ISSUE TITLE
Galactic vision msgs api change

### ISSUE THREAD

**Issue by Serafadam** [luxonis/depthai-ros#31]
Hi, there has been a slight change of API in `vision_msgs` between Foxy and Galactic, I've updated it on my branch https://github.com/Serafadam/depthai-ros/tree/galactic, I'm happy to make a PR for it (it just needs a `galactic-devel` branch on this repo) :slightly_smiling_face:

**Comment by saching13** [comment]
Yes. Thanks. Will create one.

**Comment by saching13** [comment]
Added.
