### ISSUE TITLE
Failed Building from source

### ISSUE THREAD

**Issue by Embedded1993** [luxonis/depthai-ros#315]
--- stderr: depthai_ros_driver                               
/home/ubuntu/dai_ws/src/depthai-ros/depthai_ros_driver/src/dai_nodes/sensors/imu.cpp: In constructor ‘depthai_ros_driver::dai_nodes::Imu::Imu(const string&, rclcpp::Node*, std::shared_ptr<dai::Pipeline>, std::shared_ptr<dai::Device>)’:
/home/ubuntu/dai_ws/src/depthai-ros/depthai_ros_driver/src/dai_nodes/sensors/imu.cpp:22:40: error: ‘using element_type = class dai::Device’ {aka ‘class dai::Device’} has no member named ‘getConnectedIMU’; did you mean ‘getConnection’?
   22 |     ph->declareParams(imuNode, device->getConnectedIMU());
      |                                        ^~~~~~~~~~~~~~~
      |                                        getConnection
gmake[2]: *** [CMakeFiles/depthai_ros_driver_sensor_nodes.dir/build.make:76: CMakeFiles/depthai_ros_driver_sensor_nodes.dir/src/dai_nodes/sensors/imu.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:172: CMakeFiles/depthai_ros_driver_sensor_nodes.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< depthai_ros_driver [43.9s, exited with code 2]

Summary: 5 packages finished [57.0s]
  1 package failed: depthai_ros_driver
  1 package had stderr output: depthai_ros_driver
  1 package not processed

- OS: Raspberry Pi 4B Ubuntu 22.04

-ROS distro: humble

**Comment by Serafadam** [comment]
Hi, could you check what version of `ros-humble-depthai` you have?

**Comment by innovation-x** [comment]
I have a similar situation. But it seems that I met some problems when building the mobilenet depthai examples. Also I am using the humble version of depthai and ROS.

> gmake[2]: *** [CMakeFiles/mobilenet_node.dir/build.make:211: mobilenet_node] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:173: CMakeFiles/mobilenet_node.dir/all] Error 2
> gmake: *** [Makefile:146: all] Error 2
> ---
> Failed   <<< depthai_examples [16.7s, exited with code 2]
> 
> Summary: 7 packages finished [32.6s]
>   1 package failed: depthai_examples
>   2 packages had stderr output: depthai_examples my_package
>   2 packages not processed

**Comment by Embedded1993** [comment]
Yes. I have tried humble latest version

**Comment by ladrians** [comment]
I have the same problem, but am using the `noetic` branch.

```
/home/jetson/catkin_ws/src/depthai-ros/depthai_ros_driver/src/dai_nodes/sensors/imu.cpp:23:40: error: ‘using element_type = class dai::Device’ {aka ‘class dai::Device’} has no member named
‘getConnectedIMU’; did you mean ‘getConnection’?
   23 |     ph->declareParams(imuNode, device->getConnectedIMU());
      |                                        ^~~~~~~~~~~~~~~
      |                                        getConnection

```

**Comment by Embedded1993** [comment]
Any update? still same issue

**Comment by Cur1ousKea** [comment]
Same issue for me as well. Im using Humble.

**Comment by Cur1ousKea** [comment]
Same issue for me as well. Im using Humble

**Comment by Serafadam** [comment]
Hi @Embedded1993, @Cur1ousKea, sorry for the delay, could you try running `sudo apt update` && `sudo apt ugprade`?

**Comment by Cur1ousKea** [comment]
Well, my turtlebot4 always had some hickups after upgrading thats why i feared to do it. But it solves the issue. Thanks!

**Comment by ladrians** [comment]
confirmed too that the compilation error in `noetic` branch is gone too.

**Comment by Embedded1993** [comment]
fixed
