### ISSUE TITLE
ROS2 Iron release

### ISSUE THREAD

**Issue by Serafadam** [luxonis/depthai-ros#327]

**Comment by rheaney** [comment]
Do we know when this release will be available at all? I am building a new ROS2 system and started with Iron release and found a stopping point trying to install my camera. Should I roll back to Humble?

**Comment by Serafadam** [comment]
Hey @rheaney , branch is already up, though CI seems to fail, probably due to not all packages being ported yet so I think it's going to be available after next sync, will post update after it works properly, until then you can use `iron` branch for refence.

**Comment by rheaney** [comment]
Thanks for the response, I appreciate it!

**Comment by Serafadam** [comment]
https://github.com/ros/rosdistro/pull/37793
