### ISSUE TITLE
[Help] rgbd_pcl depth data in 400p

### ISSUE THREAD

**Issue by mheyrman** [luxonis/depthai-ros#329]
I am trying to use this driver to implement an Oak-D Pro on a robot, specifically using the rgbd_pcl package, however, I am having speed issues and to alleviate these I would like to use the 400p resolution for all ROS messages, and specifically need that aspect ratio for properly running on my model. However, I cannot figure out how to change the resolutions from 720p, which is also the wrong aspect ratio. I have tried adjusting all of the camera.yaml values in depth_ros_driver to match my desired resolution, but this has no effect. Are there more specific instructions somewhere to correctly change the resolution to 400p?

 I only need the raw stereo image data, so if there are any other ways that I could potentially speed up the process, I'd love to hear it. 

Thanks.

**Comment by Serafadam** [comment]
Hi!
- `rgbd_pcl` has a separate parameter file in the configs, you can also load your own parameter file using launch arguments
- To lower resolutions, you can try setting RGB parameters, you can check parameters [here ](https://github.com/luxonis/depthai-ros#setting-rgb-parameters). When it comes to ISP scaling, you can refer to [this document](https://docs.google.com/spreadsheets/d/153yTstShkJqsPbkPOQjsVRmM8ZO3A6sCqm7uayGF-EE/edit#gid=0), only modify resolution dimensions to the one that you set for the camera and check the lines where it's all green (I think for 1080P lowest ratio you can get is 1/5).

**Comment by mheyrman** [comment]
I see, thank you! I was under the incorrect impression that the various parameter files contributed differently, thank you for informing me. I was able to get it working as desired by editing `rgbd_pcl.yaml`. Though it seems that for the extended disparity mode exceeds the maximum supported disparity of the Median Filter so it does not work.

Thank for you the help.
