### ISSUE TITLE
source /opt/ros/<ros-distro>/setup.bash: no such file

### ISSUE THREAD

**Issue by Charles-Li26** [luxonis/depthai-ros#34]
Hi,
I'm new in ROS, so after I successfully did the first 5 steps. Now, in the step 6, there is no such file address of opt/ros/...

Thank you,
CL

**Comment by saching13** [comment]
I think you have not installed ros. You need to install the appropriate Ros version depending on your OS.

**Comment by Charles-Li26** [comment]
So for the <ros-distro> , does it mean the version of ROS, like I stalled ROS noetic, so I need to fill neotic at that plave. Am I right?

CL

**Comment by Charles-Li26** [comment]
So for the <ros-distro >, does it mean the version of ROS, like I stalled ROS noetic, so I need to fill "neotic" at that place. Am I right?

CL

**Comment by Charles-Li26** [comment]
So for the "ros-distro", does it mean the version of ROS, like I stalled ROS noetic, so I need to fill "neotic" at that place. Am I right?

CL

**Comment by saching13** [comment]
> So for the "ros-distro", does it mean the version of ROS, like I stalled ROS noetic, so I need to fill "neotic" at that place. Am I right?
> 
> CL

Yes.

**Comment by Charles-Li26** [comment]
All right, thank you so much. And now I am working on the catkin_make and it shows same error as "ans-qureshi" had. Hopeful that I can solve this error based your comments. 

CL

**Comment by saching13** [comment]
But you shouldn't need to pass the path like in #2  since the depthai is installed to the system

**Comment by Charles-Li26** [comment]
![Screenshot from 2021-10-01 11-47-59](https://user-images.githubusercontent.com/78176689/135650337-73e370a6-bff0-4dea-84d7-c9ef6c552c57.png)
With the "catkin_make" commend, I got the same error. But there is one difference which is the #2 has 4 packages which I only got 3 package, the vision-msgs missed.

**Comment by Charles-Li26** [comment]
And I cannot find these two documents that mentioned above which are "depthaiConfig.cmake" and "depthai-config.cmake"

**Comment by saching13** [comment]
Looks like install dependencies didn't go well on yours. Can you do it again ? it should be installed in `usr/local`
Link [here](https://github.com/luxonis/depthai-ros#install-dependencies)

**Comment by Charles-Li26** [comment]
![Screenshot from 2021-10-01 12-27-00](https://user-images.githubusercontent.com/78176689/135655373-340a2b9e-435e-4dc9-8114-cb3848465c83.png)
In the Install Dependencies section, all the other parts are installed right. Just the fist step has some problem and is that caused the mistake in catkin_make?

**Comment by saching13** [comment]
it is not. it is failing. Your docker installation keys are missing. The command that is failing is `sudo apt update` I think. You need to fix those ppa installation keys

**Comment by Charles-Li26** [comment]
Thank you for your time. All the procedures execute well. And I am moving to the example execution section now. I'm using Oak-D camera to connect to my computer and when I execute the stereo_node.launch commend. I only able to hear a "click" sound from camera and nothing happened. 
![Screenshot from 2021-10-01 13-10-35](https://user-images.githubusercontent.com/78176689/135660365-01a2c524-b877-4648-853a-9c3c1cc9d29e.png)
.

**Comment by saching13** [comment]
They are being published on ROS topics. you can run `rqt_image_view` and select the topic of the image you want to see. or use `rviz`

**Comment by Charles-Li26** [comment]
Thank you so much for bearing me. The rqt_image_view and rviz are working well now.
