### ISSUE TITLE
[Feature-Request] {Add adjusting disparity shift to ros driver for noetic}

### ISSUE THREAD

**Issue by lpengample** [luxonis/depthai-ros#342]
### Start with the `why`:
I'm using the OAK-D Pro Poe to detect objects within 400mm to 900m depth range and adjusting disparity shift to detect depth in a limited close range would be very helpful without losing quality as a result of to decreasing resolution. 

### Move to the `what`:
Having disparity shift as described in documentation [here](https://docs.luxonis.com/projects/api/en/latest/tutorials/configuring-stereo-depth/#disparity-shift) configurable through parameters we can set in the roslaunch file or config/xxxx.yaml folder.

**Comment by Serafadam** [comment]
Disparity shift has been added in one of the new releases, closing this issue as completed.
