### ISSUE TITLE
[BUG] {Compilation of package with ROS Noetic on RPI4 make it crashed  }

### ISSUE THREAD

**Issue by ChengTszYin** [luxonis/depthai-ros#353]
I tried to install the package from source on my RPI 4B which installed with ROS Noetic. I compile the package with `catkin_make` but it crashed everytimes I tried. Are there any solution available on my case? Thank you
<img width="1021" alt="螢幕截圖 2023-07-22 下午9 43 21" src="https://github.com/luxonis/depthai-ros/assets/97682712/913183a1-a300-4188-ad9c-3e8118986404">

**Comment by Serafadam** [comment]
Hi, to limit resource usage during compilation you can execute `MAKEFLAGS="-j1 -l1" catkin_make_isolated`, you can also temporarily increase [RAM with swap](https://pimylifeup.com/raspberry-pi-swap-file/)

**Comment by ChengTszYin** [comment]
Thank, I successfully built it. It is my fault.
