### ISSUE TITLE
ERROR: the following packages/stacks could not hace their rosdep keys resolved to system dependencies

### ISSUE THREAD

**Issue by bb6698** [luxonis/depthai-ros#355]
Hi! I have installed ros2 distribution humble since installation source in the Nvidia Jetson AGX Orin. I want install depthai-ros. 

I try rosdep install --from-paths src --ignore-src -r -y following instructions install from source package:depthai-ros. 

The problem is: 
![Captura desde 2023-07-27 10-22-46](https://github.com/luxonis/depthai-ros/assets/73492480/f8d578c3-afd5-4ecb-bf81-c1d6b6db1ad7)

I try also rosdep install --from-paths src --ignore-src -r --rosdristro humble but I have same error. 

Please, Can anybody help me? 

Cheers.

**Comment by Serafadam** [comment]
Hi, default ROS distro for focal is Foxy (which is end-of-life), so even if you install Humble from source you won't be able to access humble packages via rosdep. Easiest way to get that system is to use Docker images https://github.com/dusty-nv/jetson-containers

**Comment by bb6698** [comment]
Thanks for your answer!! I'll follow your advice :)

**Comment by Serafadam** [comment]
Closing, please reopen if needed.
