### ISSUE TITLE
Error 'function is deprecated' when building the package for foxy

### ISSUE THREAD

**Issue by ericdepotter** [luxonis/depthai-ros#36]
Hi,

I just tried to install this package for the foxy ROS version. Unfortunately I get a build error in the step  `colcon build` stating that a certain function is deprecated. The error is shown below. 

> Starting >>> depthai_ros_msgs
[0.269s] WARNING:colcon.colcon_ros.prefix_path.catkin:The path '/home/eric/catkin' in the environment variable CMAKE_PREFIX_PATH doesn't exist
Finished <<< depthai_ros_msgs [4.42s]                     
Starting >>> depthai_bridge
Finished <<< depthai_bridge [8.53s]                      
Starting >>> dai_turtlebot3_description
Starting >>> depthai_examples
Finished <<< dai_turtlebot3_description [12.1s]
--- stderr: depthai_examples                                
/home/eric/Projecten/DepthAI/ROS/src/luxonis/depthai-ros-examples/depthai_examples/lib/stereo_pipeline.cpp: In member function ‘void StereoExample::initDepthaiDev()’:
/home/eric/Projecten/DepthAI/ROS/src/luxonis/depthai-ros-examples/depthai_examples/lib/stereo_pipeline.cpp:50:43: warning: ‘void dai::node::StereoDepth::setConfidenceThreshold(int)’ is deprecated: Use 'initialConfig.setConfidenceThreshold()' instead [-Wdeprecated-declarations]
   50 |         stereo->setConfidenceThreshold(200);
      |                                           ^
In file included from /usr/local/include/depthai/pipeline/nodes.hpp:19,
                 from /usr/local/include/depthai/depthai.hpp:17,
                 from /home/eric/Projecten/DepthAI/ROS/src/luxonis/depthai-ros-examples/depthai_examples/include/depthai_examples/stereo_pipeline.hpp:5,
                 from /home/eric/Projecten/DepthAI/ROS/src/luxonis/depthai-ros-examples/depthai_examples/lib/stereo_pipeline.cpp:1:
/usr/local/include/depthai/pipeline/node/StereoDepth.hpp:175:81: note: declared here
  175 | se 'initialConfig.setConfidenceThreshold()' instead")]] void setConfidenceThreshold(int confThr);
      |                                                              ^~~~~~~~~~~~~~~~~~~~~~
Finished <<< depthai_examples [13.8s]
Summary: 4 packages finished [26.8s]
  1 package had stderr output: depthai_examples

Kind regards,
Eric

**Comment by saching13** [comment]
those are just deprecation warnings from depthai which ros2 shows as errors. Just build again it will go through. 
I am working on an update to remove those warnings..
