### ISSUE TITLE
Error: Resolution bigger than maximum

### ISSUE THREAD

**Issue by julianhund** [luxonis/depthai-ros#360]
Im using Oak-D-Pro-W-97 and ros2-humble
I have the following error when I launch camera.launch.py of the depthai_ros_driver package:

"[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'oak' of type 'depthai_ros_driver::Camera' in container '/oak_container': Component constructor threw an exception: ColorCamera(0) - 'video' width or height (1280, 720) bigger than maximum at current sensor resolution (854, 534)"

Launch-file:
1691130005.2882426 [INFO] [launch]: All log files can be found below /home/julian/.ros/log/2023-08-04-08-20-05-287520-julian-ThinkPad-L490-5887
1691130005.2883549 [INFO] [launch]: Default logging verbosity is set to INFO
1691130005.6257164 [INFO] [robot_state_publisher-1]: process started with pid [5904]
1691130005.6259181 [INFO] [component_container-2]: process started with pid [5906]
1691130005.6548066 [robot_state_publisher-1] [INFO] [1691130005.654550170] [oak_state_publisher]: got segment oak
1691130005.6553915 [robot_state_publisher-1] [INFO] [1691130005.655212690] [oak_state_publisher]: got segment oak-d-base-frame
1691130005.6557660 [robot_state_publisher-1] [INFO] [1691130005.655351986] [oak_state_publisher]: got segment oak_imu_frame
1691130005.6558864 [robot_state_publisher-1] [INFO] [1691130005.655364852] [oak_state_publisher]: got segment oak_left_camera_frame
1691130005.6559782 [robot_state_publisher-1] [INFO] [1691130005.655373450] [oak_state_publisher]: got segment oak_left_camera_optical_frame
1691130005.6560707 [robot_state_publisher-1] [INFO] [1691130005.655381589] [oak_state_publisher]: got segment oak_model_origin
1691130005.6561615 [robot_state_publisher-1] [INFO] [1691130005.655389206] [oak_state_publisher]: got segment oak_rgb_camera_frame
1691130005.6562457 [robot_state_publisher-1] [INFO] [1691130005.655396637] [oak_state_publisher]: got segment oak_rgb_camera_optical_frame
1691130005.6563303 [robot_state_publisher-1] [INFO] [1691130005.655404261] [oak_state_publisher]: got segment oak_right_camera_frame
1691130005.6564093 [robot_state_publisher-1] [INFO] [1691130005.655413045] [oak_state_publisher]: got segment oak_right_camera_optical_frame
1691130005.8796866 [component_container-2] [INFO] [1691130005.879163666] [oak_container]: Load Library: /home/julian/Software/Assemblyassist/dai_ws/install/depthai_ros_driver/lib/libdepthai_ros_driver.so
1691130005.9675229 [component_container-2] [INFO] [1691130005.967208517] [oak_container]: Found class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
1691130005.9677582 [component_container-2] [INFO] [1691130005.967276317] [oak_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<depthai_ros_driver::Camera>
1691130005.9765518 [component_container-2] [INFO] [1691130005.976050234] [oak]: No ip/mxid specified, connecting to the next available device.
1691130008.4309049 [component_container-2] [INFO] [1691130008.430647800] [oak]: Camera with MXID: 18443010E1EE870E00 and Name: 1.1 connected!
1691130008.4316204 [component_container-2] [INFO] [1691130008.431441723] [oak]: USB SPEED: SUPER
1691130008.4533288 [component_container-2] [INFO] [1691130008.452640240] [oak]: Device type: OAK-D-PRO-W-97
1691130008.4556460 [component_container-2] [INFO] [1691130008.454996653] [oak]: Pipeline type: RGBD
1691130008.4750526 [component_container-2] [INFO] [1691130008.474498593] [oak]: NN Family: mobilenet
1691130008.6210980 [component_container-2] [INFO] [1691130008.620798154] [oak]: NN input size: 300 x 300. Resizing input image in case of different dimensions.
1691130008.9908464 [component_container-2] [INFO] [1691130008.990133760] [oak]: Finished setting up pipeline.
1691130009.1933334 [component_container-2] [18443010E1EE870E00] [1.1] [1.487] [ColorCamera(0)] [warning] Unsupported resolution set for detected camera OV9782, needs 800_P or 720_P. Defaulting to 800_P
1691130011.4340112 [component_container-2] [ERROR] [1691130011.433268928] [oak_container]: Component constructor threw an exception: ColorCamera(0) - 'video' width or height (1280, 720) bigger than maximum at current sensor resolution (854, 534)
1691130011.4364607 [ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'oak' of type 'depthai_ros_driver::Camera' in container '/oak_container': Component constructor threw an exception: ColorCamera(0) - 'video' width or height (1280, 720) bigger than maximum at current sensor resolution (854, 534)
1691130035.4851186 [WARNING] [launch]: user interrupted with ctrl-c (SIGINT)
1691130036.4734519 [component_container-2] [INFO] [1691130035.484553123] [rclcpp]: signal_handler(signum=2)
1691130036.4744947 [INFO] [robot_state_publisher-1]: process has finished cleanly [pid 5904]
1691130036.4752407 [INFO] [component_container-2]: process has finished cleanly [pid 5906]
1691130036.4766872 [robot_state_publisher-1] [INFO] [1691130035.484553441] [rclcpp]: signal_handler(signum=2)

**Comment by Serafadam** [comment]
Hi, currently default parameters are set for OAK-D-PRO (not W), so if you want to use the camera you should update the parameters ([there is also a separate parameter file for OAK-D-PRO-W](https://github.com/luxonis/depthai-ros/blob/humble/depthai_ros_driver/config/oak_d_pro_w.yaml))
