### ISSUE TITLE
[Question] IMU + rgb + depth timestamp syncing

### ISSUE THREAD

**Issue by michaelnguyen11** [luxonis/depthai-ros#451]
Hi Authors,

I would like to use the OAK-D Pro camera with our VIO/SLAM algorithm, and the VIO/SLAM algorithm requires syncing IMU messages and camera frames. As far as I understand, the depthai-ros don't support this kind of feature right now.

So my questions are:
- Do depthai-ros intend to implement this feature?
- If I want to implement this kind of feature by myself, could you please give me some advice on how to implement it within depthai-ros?

Many thanks in advance!

Best regards,
Michael Nguyen

**Comment by Serafadam** [comment]
Hi, multiple message syncing will be available in one of the next releases (as soon as the features are available in `depthai-core`. Regarding current approaches, you could try writing a node in C++ where you create the queues and then sync them based on timestamp/sequence number, after they are synced you can assign them the same timestamp and publish them with specific publishers.

**Comment by michaelnguyen11** [comment]
Hi @Serafadam ,

Thank you for the information. Hope to use the multiple message syncing soon.
