### ISSUE TITLE
[Question] Is there a way to stop publishing the compressed image topics?

### ISSUE THREAD

**Issue by vladmosoiu98** [luxonis/depthai-ros#476]
Hello,

I would like to know if there is a way (ideally through the parameter configuration file) to stop publishing the compressed topics for each component. I know that depthai is using the `image_transport` package for the publishing of the imaging, but I could not figure out how to disable the compression.

```
/oak/nn/passthrough/image_raw/compressed
/oak/nn/passthrough/image_raw/compressedDepth
/oak/nn/passthrough/image_raw/theora
/oak/rgb/image_raw/compressed
/oak/rgb/image_raw/compressedDepth
/oak/rgb/image_raw/theora
```

I need this information because every time I subscribe to one of those topics (for example when opening Foxglove where I can not bypass some of the topics), my terminal is flooded with errors, such as:
```
[ERROR] [1704743237.583933472] [compressed_depth_image_transport]: Compressed Depth Image Transport - Compression requires single-channel 32bit-floating point or 16bit raw depth images (input format is: bgr8).
[ERROR] [1704743343.808687872] [CompressedPublisher]: [16UC1] is not a color format. but [mono8] is. The conversion does not make sense
[ERROR] [1704743421.184808416] [TheoraPublisher]: cv_bridge exception: '[16UC1] is not a color format. but [bgr8] is. The conversion does not make sense'
```

My initial approach was like this:
```
/oak:
  ros__parameters:
    rgb:
      image_raw:
        disable_pub_plugins: 'image_transport/compressed'
```
but from what I understand the "disable_pub_plugins" is not yet available in ROS2 Humble.

If you have any suggestions or approaches for such a problem, please let me know! Thank you!

**Comment by Serafadam** [comment]
Hi, AFAIK this functionality is not yet available in Humble (see [link ](https://github.com/ros-perception/image_common/pull/264)), one way to mitigate this would be to run the node in [intra-process mode ](https://docs.ros.org/en/iron/Tutorials/Demos/Intra-Process-Communication.html?highlight=intra) as in that case "bare" publishers are initialized in place of image_transport ones.

**Comment by vladmosoiu98** [comment]
Hi Adam, 
Thanks for the answer, I will try the intra-process mode for now.

**Comment by stanislawix** [comment]
@Serafadam are you sure it's not merged into neither humble nor jazzy? It was merged into rolling almost 2 years ago.
And I can't see the PR-associated commits when looking at diff between (rolling, humble) nor (rolling, jazzy)...

**Comment by Serafadam** [comment]
Hi, I haven't tested it but it seems that this was [merged few months](https://github.com/ros-perception/image_common/pull/302/files) after last reply here

**Comment by DanieleMarchisotti** [comment]
@Serafadam I am using ROS2 Humble.
Is this functionality now available? Have you tested it?
Should I add this to the `camera.yaml` file?
```
/oak:
  ros__parameters:
    rgb:
      image_raw:
        disable_pub_plugins: 'image_transport/compressed'
```

**Comment by Serafadam** [comment]
Hi @DanieleMarchisotti, I just tested it and it seems to work fine
