### ISSUE TITLE
[custom] Looking for a OAK-D Short Range.stl

### ISSUE THREAD

**Issue by notalfredo** [luxonis/depthai-ros#488]
Howdy, I was wondering if you Luxonis was going to add an stl file for the OAK-D Short Range Camera. I am not sure if one already exist I looked around in the main branch and in other branches for one.

**Comment by Serafadam** [comment]
Hi, STL models in `depthai_descriptions` will be updated soon (hopefully next week). Tagging @danilo-pejovic

**Comment by notalfredo** [comment]
Closing issue #491 resolved
