### ISSUE TITLE
[BUG] ROS Documentation link goes to 404 Error page

### ISSUE THREAD

**Issue by tweng-bdai** [luxonis/depthai-ros#503]
https://docs-beta.luxonis.com/develop/ros/depthai-ros-intro/ returns 404. The link is in the README of this repo. I have accessed this page previously but am unable to access it now. 

Repro'd on several browsers and networks.

**Comment by Serafadam** [comment]
Hi, thanks, link has been updated on the main branch.

**Comment by gestalt73** [comment]
https://docs-beta.luxonis.com/software/ros/depthai-ros/intro/ is the link on the default branch "humble"

I'm still getting a cloudfare 404 error.

**Comment by raymondsong00** [comment]
I was trying build from source but couldn't find the steps anymore. The "build from source" and "driver" options that are linked options on the docs returns "unexpected error occurred" and the hyperlink from the intro tab returns a 404.

**Comment by Serafadam** [comment]
Hi, thanks for notifying, this was caused by some error in the docs, those pages should be online now.
