### ISSUE TITLE
Wants depthai-core v2.24.0 in ROS repository

### ISSUE THREAD

**Issue by borongyuan** [luxonis/depthai-ros#506]
Hi @saching13 @Serafadam,

Could you update depthai-core in the ROS repository to v2.24.0? I've added support for OAK internal sync in RTAB-Map https://github.com/introlab/rtabmap/pull/1193. We have not merged this part yet because we wanted to avoid causing trouble for users who installed depthai-core from the ROS repository. But recently I am trying to add HF-Net feature, which is more powerful than SuperPoint https://github.com/introlab/rtabmap/issues/1215. So we want to merge the previous parts soon.

**Comment by Serafadam** [comment]
Hi @borongyuan , thanks for the report, we will add the new release this week. Also, I wanted to mention that we are currently working on integrating RTABMAP's VIO/SLAM in new Odom/SLAM nodes in depthai-core that will be part of V3 release.

**Comment by Serafadam** [comment]
DepthAI v2.24.0 [is released](https://index.ros.org/p/depthai/github-luxonis-depthai-core/#humble)

**Comment by borongyuan** [comment]
Thanks!
