### ISSUE TITLE
Option to sync raw left/right streams

### ISSUE THREAD

**Issue by aatb-ch** [luxonis/depthai-ros#509]
For a VIO project, I need exact match on timestamps for left/right image raw streams.

I found https://github.com/luxonis/depthai-ros/issues/421 mentionning the option `stereo_i_publish_synced_rect_pair: true` which is exactly what I need but not on rectified streams, I need raw streams.

Any way to get this option also for left/right raw streams? For now I managed a workaround to not use exact timestamps but this potentially degrades the tracking quality.

**Comment by Serafadam** [comment]
Hi, currently there is no option for syncing raw messages, I think the simplest option would be to create a small node similar to ones in depthai_examples to publish data with exact sync.

**Comment by aatb-ch** [comment]
Thanks for the quick reply.

I am currently using ROS ApproximateTime sync policy to workaround, the original code used the ExactTime policy which requires perfect match. So "it works" like that, even though it would have been easier the other way.

Alright yes, I see, then if I must improve that part I will write a node and publish the raw frames myself. Thanks!
