### ISSUE TITLE
Mapping approaches for spatial object detection

### ISSUE THREAD

**Issue by FlorianMehnert** [luxonis/depthai-ros#512]
Hi there,

I was wondering if there exists a solution tested with the spatial_bb node to remember the 3d position of annotated objects in long term memory. This is a follow up question to #450

**Comment by Serafadam** [comment]
Hi, as of now there is no such example in this repository, but in theory it should be pretty straightforward to create another node that subscribes to this information and keeps it in memory/in a file. I think a good reference could be[ this project](https://github.com/ROBOTIS-JAPAN-GIT/turtlebot3_slam_3d).

**Comment by Serafadam** [comment]
Closing this issue, if you have further questions please feel free to reopen it.
