### ISSUE TITLE
When launch the OAK-D LR camera, it stops other USB device from working

### ISSUE THREAD

**Issue by hangcui1201** [luxonis/depthai-ros#519]
Hi,

We have made our OAK-D LR camera work with the depthai_ros_driver through the USB 3.1 cable. 

**However, we found whenever we launched the OAK-D LR camera using the depthai_ros_driver, it stopped our another USB device from working.** In our case, it is the Septentrio GNSS-INS device. It uses the USB 2.0 cable, USB-Over-Ethernet protocol. The heading information became N/A. Whenever we stopped launching the OAK-D LR camera, the heading information became available again. 

![Screenshot from 2024-03-27 17-54-40](https://github.com/luxonis/depthai-ros/assets/37420029/59d59136-9d94-4c93-969e-07a4f5b6b0d0)

![Screenshot from 2024-03-27 17-55-07](https://github.com/luxonis/depthai-ros/assets/37420029/9a60e1c2-8000-4871-9099-2b3794bf76ca)

The GNSS-INS device was powered independently from the 12V power source. The OAK-D LR camera was powered through the USB 3.1 cable. We also used a USB 3.1 boost extension cable and we added an additional 5V power to that extension cable. **So we think such issue should not be due to the power supply.** 

We also tried to launch the OAK-D LR camera with streaming videos only from the center len. It still did not work. **So the issue should not be due to the USB bandwidth, either.** We tried different USB ports. The results were the same.  Whenever we launched the OAK-D LR camera using the depthai_ros_driver, it stopped our GNSS-INS USB device from working. 

We have no idea what happened. **Is it possible that whenever we launched the OAK-D LR camera, it used some USB protocol that stopped the GNSS-INS USB device from working?** Any other suggestions?

Thanks a lot for the help!

Best,
Hang

**Comment by Serafadam** [comment]
Hi, could you post some more information following the [bug report template](https://github.com/luxonis/depthai-ros/blob/humble/.github/ISSUE_TEMPLATE/bug_report.md)?

**Comment by hangcui1201** [comment]
Hi Serafadam,

Sorry, we found it was the IMU initialization issue of the other USB GNSS/INS device.

Best,
Hang

**Comment by Serafadam** [comment]
Thanks for the information, closing the issue.
