### ISSUE TITLE
URDF Plugin

### ISSUE THREAD

**Issue by kursatkomurcu** [luxonis/depthai-ros#523]
Hello Community,

I want to use luxonis camera in my urdf file for drone. Are there any tutorial for this?

**Comment by Serafadam** [comment]
Hi, there is no specific example in this repository, but just following the [xacro tutorial](http://wiki.ros.org/xacro#Including_other_xacro_files) and including/configuring [depthai_descr.urdf.xacro](https://github.com/luxonis/depthai-ros/blob/humble/depthai_descriptions/urdf/depthai_descr.urdf.xacro) in your URDF should get you there.
