### ISSUE TITLE
[BUG] Missing depthai-ros packages on Noetic

### ISSUE THREAD

**Issue by ptoupas** [luxonis/depthai-ros#543]
Hi,

I am having some issues installing depthai-ros on Ubuntu 20.04. It seems like there has been some recent update and some packages of the ros-noetic-depthai-* are missing and cannot be installed. I can only install some of them (but the main ones seems to be missing like depthai-ros for example or the depthai-ros-driver)
I had previously installed them at the same OS some time ago but it seems like I cant do this anymore.

This issue is also probably related to issue #540

**Comment by Serafadam** [comment]
Hi, yes, it the new release of depthai broke builds for depthai-ros (this is fixed now), but according to the latest release post they should be back (and they aren't, respective issue created in rosdistro https://github.com/ros/rosdistro/issues/41775)

**Comment by ptoupas** [comment]
Thanks a lot. It seems to be fixed now!
