### ISSUE TITLE
how to adapt imu extrinsics after stereo rectification

### ISSUE THREAD

**Issue by lturing** [luxonis/depthai-ros#562]
from [depthai-boards](https://github.com/luxonis/depthai-boards/tree/main/boards), we can get imu extrinsics accordingly. and after stereo rectfication, how to get the corresponding imu extrinsics

**Comment by Serafadam** [comment]
Hi, sorry for the delay, those extrinsics should correspond to rectified stereo setup, if that is not the case you can try recalibrating the device using for example [Kalibr](https://github.com/ethz-asl/kalibr). A built-in IMU calibration method is on the roadmap but at this moment it is hard to say when it will be available.
