### ISSUE TITLE
oak-d pro terrible depth pointcloud

### ISSUE THREAD

**Issue by khuechuong** [luxonis/depthai-ros#563]
Device: oak-d pro poe
ROS: Noetic

I haven't done any calibration on it, but I feel like even if I didn't, it shouldn't be this bad.

```
roslaunch depthai_ros_driver rgbd_pcl.launch
```
gives me a terrible pointcloud in rviz:
![image](https://github.com/user-attachments/assets/5cdc0ec3-e9b9-4b5a-91b6-ffadf53596cd)

I ran the code given [here](https://docs.luxonis.com/software/depthai/examples/pointcloud_visualization/) and it's the same. 
![image](https://github.com/user-attachments/assets/2b708c24-854b-454e-9119-5086c13017d8)

Here's the depth preview:
![image](https://github.com/user-attachments/assets/bbfc426a-c902-4f1a-af5b-bed17ddeb30a)

What should I do?

**Comment by Serafadam** [comment]
Hi, if the pointcloud quality is bad on non-ROS side, something might be wrong with the device calibration, please send us an email with order details on support@luxonis.com

**Comment by khuechuong** [comment]
@Serafadam I just did. When can I expect a response? Thank you!

**Comment by Serafadam** [comment]
Hi, sorry for the delay, response probably should have already arrived, if not please leave a comment.
