### ISSUE TITLE
[custom] modifying stereo parameter with dynamic reconfig

### ISSUE THREAD

**Issue by khuechuong** [luxonis/depthai-ros#568]
I'm trying to figure out where I can do this:

![image](https://github.com/user-attachments/assets/d3485148-847e-42f4-9b8f-04baf8dd7912)

which launch file does that? I'm using ROS Noetic

**Comment by Serafadam** [comment]
Hi, this is done via [rqt tool](https://wiki.ros.org/rqt), more specifically using image view and dynamic_reconfigure plugins

**Comment by khuechuong** [comment]
@Serafadam yes, but when I ran the camera.launch and did rqt, and add it using image view and dynamic_reconfigure plugins, I didn't see this oak.

**Comment by khuechuong** [comment]
@Serafadam 
![rqt](https://github.com/user-attachments/assets/2f959dd9-02fa-45f8-9dfc-a0488dc72f19)

**Comment by khuechuong** [comment]
@Serafadam any updates? does it not appear b/c the noetic branch didn't have the node for it?

**Comment by Serafadam** [comment]
Hi, sorry, I had written a response but it seems it wasn't published. To get the full list of parameters you need to click on `oak`, ROS1 parameters aren't namespaced properly as in ROS2 due to some limitations.

**Comment by khuechuong** [comment]
@Serafadam as u can see in this picture ![picture](https://github.com/user-attachments/assets/2f959dd9-02fa-45f8-9dfc-a0488dc72f19), 

that's all the parameter that's available to me in dynamic reconfigure. I don't see the depth or rgb or stereo parameters like confidence or IR, etc

**Comment by khuechuong** [comment]
nvmd got it
