### ISSUE TITLE
[Feature-Request] {Oak-D Pro.yaml file with all sensor options enabled}

### ISSUE THREAD

**Issue by AncientGrey** [luxonis/depthai-ros#579]
### Start with the `why`:
A generic config file for the Oak-D Pro with all sensor enabled would make configuration easier and give easier access to all possible use case for the camera.

### Move to the `what`:
Generating a .yaml file for the configuration of the Oak-D Pro camera with all config features and sensors (IMU, Stereo-Depth, RGB, etc.) enabled and possible all potential values a parameter could take as comments.

**Comment by Serafadam** [comment]
Hi, such file can be found in the [official docs](https://docs.luxonis.com/software/ros/depthai-ros/driver/#DepthAI%20ROS%20Driver-List%20of%20parameters), is that what you mean?

**Comment by AncientGrey** [comment]
Perfect, yes that is what i mean. Thank you.
