### ISSUE TITLE
Could not find a package 【depthai】

### ISSUE THREAD

**Issue by berlin2049** [luxonis/depthai-ros#61]
install the 【depthai-core】：https://github.com/luxonis/depthai-core

and edit 【depthai-ros】's CmakeLists.txt line 21 【find_package(depthai CONFIG REQUIRED)】to
【find_package(depthai CONFIG REQUIRED PATHS "your depthai-core/build/install/lib/cmake/depthai")】

**Comment by themarpe** [comment]
@berlin2049 if I understood your issue at hand is that doing manual compilation locally required you to specify the build directory of depthai-core manually, by modifying the CMakeLists.txt of depthai-ros.

This can by also done by either:
 - Setting ENV variable: `depthai_DIR="path/to/build/or/install/directory"`
 - Specifying CMake configuration define: `-D depthai_DIR="path/to/build/or/install/directory"`
