### ISSUE TITLE
[Question] Is image timestamp same as detection timestamp?

### ISSUE THREAD

**Issue by MRo47** [luxonis/depthai-ros#617]
## Context
- I'm trying to find the latency of the Stereo pipeline with NN enabled on left camera.
- Want to know if the detection timestamp includes the time to process the image (NNinput -> detection).
- lets call image timestamp: `ti`
- detection timestamp: `td`
- time to process image in detection NN: `tnn`

## Question
What does the device return on the following calls in 
- [ImgDetectionConverter.cpp](https://github.com/luxonis/depthai-ros/blob/9132443a85381f118e75d8583df3d9e764a91b7a/depthai_bridge/src/ImgDetectionConverter.cpp#L33)
- [ImageConverter.cpp](https://github.com/luxonis/depthai-ros/blob/9132443a85381f118e75d8583df3d9e764a91b7a/depthai_bridge/src/ImageConverter.cpp#L89)

Can u provide an answer using the above convention?

**Comment by Serafadam** [comment]
Hi, the NN data timestamp is taken from ImageFrame that was used for the inference, unfortunately there is no easy way to get the actual processing time. You could try setting `DEPTHAI_LEVEL=trace` env variable to get information on how long the inference took from the logs

**Comment by MRo47** [comment]
@Serafadam this answers my question. Thank you
