### ISSUE TITLE
catkin_make "depthai_bridge" failed

### ISSUE THREAD

**Issue by berlin2049** [luxonis/depthai-ros#62]
![474a09fd34177e71efde7468d323d55](https://user-images.githubusercontent.com/52685943/150631063-cb2c67ed-8346-47e7-8993-f6634e2e2aa2.png)

JetsonNano 
Ubunt18.04 
ROS-Melodic

has anyone met this error?

**Comment by themarpe** [comment]
@berlin2049 
Please try again, but remove Hunter cache first (`rm -r ~/.hunter`)
This issue can arise when core is built as static library and then as a shared library (eg. by setup commands in the ROS steps)

CC: @saching13 - I suggest specifying `-D HUNTER_ROOT=[some/path/in/build/directory]` just to remove any dependence on cached (or miscached) results from previous compilations of depthai-core. 
(background - Hunter doesn't get the PIC flag properly and doesn't create a new cache "tag", which then causes libraries built without -fPIC and with -fPIC to misrepresent as one or the other)
