### ISSUE TITLE
[Feature-Request] { using Docker with the ROS2 Jazzy image.}

### ISSUE THREAD

**Issue by sfeng97** [luxonis/depthai-ros#622]
"I am using Docker with the ROS2 Jazzy image. I downloaded your package, but during compilation, I got the error:

--- stderr: depthai_examples
CMake Error at CMakeLists.txt:41 (file):
file DOWNLOAD cannot compute hash on failed download
status: [28;"Timeout was reached"]

What could be the cause of this?"

**Comment by sfeng97** [comment]
![image](https://github.com/user-attachments/assets/2d8e72f8-e37c-4222-a0d9-969f1af218b9)

**Comment by Serafadam** [comment]
Hi, do you have access to internet connection on that machine? `depthai_examples` download NN blobs while building so that issue is related to download, either by network issue (connection or server error)

**Comment by sfeng97** [comment]
thanks


--------------原始邮件--------------
发件人："Adam&nbsp;Serafin ***@***.***&gt;;
发送时间：2024年11月9日(星期六) 凌晨0:02
收件人："luxonis/depthai-ros" ***@***.***&gt;;
抄送："石峰 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [luxonis/depthai-ros] [Feature-Request] { using Docker with the ROS2 Jazzy image.} (Issue #622)
-----------------------------------

 

 
Hi, do you have access to internet connection on that machine? depthai_examples download NN blobs while building so that issue is related to download, either by network issue (connection or server error)
