### ISSUE TITLE
how to synchronize multi oak-d-sr?

### ISSUE THREAD

**Issue by lturing** [luxonis/depthai-ros#632]
hi, i have two oak-d-sr devices(name oak_d_sr_1 and oak_d_sr_2), want to use these two to estimate depth from camera_left_in_oak_d_sr_1 and camera_right_in_oak_d_sr_2, which will have the desired bigger baseline length than 2cm and can also output rgb image.     
for stereo depth estimation, the algorithm in deep learning need synchronized left/right pairs, so how to synchronize the two devices and output the synchronized left/right pairs? the left image from device oak_d_sr_1 and the right image from device oak_d_sr_2, just like the left/right pair in one device.

**Comment by Serafadam** [comment]
Hi, for syncing multiple devices I would try using [message_filters](http://wiki.ros.org/message_filters) in ROS, similarly to how topics are synced for examples in `depthai_filters`
