### ISSUE TITLE
Right side of PoindCloud is lacking.

### ISSUE THREAD

**Issue by nisshan-x** [luxonis/depthai-ros#66]
Hi,

I bought OAK-D Lite (kickstarter version), installed depthai-ros according to README.md to Ubuntu 20, and launched `roslaunch depthai_examples stereo_nodelet.launch` . But Right side of PoindCloud in Rviz is lacking.

![oak_d_lite_depth_only_left1](https://user-images.githubusercontent.com/67353276/153001645-0be69fdd-0211-4c50-bf33-dfb57eed7854.png)

I tried to run `depthai_demo.py`. Then both left and right side of depth image appeared. I guess OAK-D Lite hardware and USB connection are fine.
![oak_d_lite_depth_image_3](https://user-images.githubusercontent.com/67353276/153001788-52595fa2-617b-4fba-93a9-264afac16513.png)

Could you please tell me how to deal with this problem?

**Comment by nisshan-x** [comment]
A different angle of view.

![oak_d_lite_depth_only_left2](https://user-images.githubusercontent.com/67353276/153002397-988895f8-94c7-499e-add7-c7b766e513af.png)

**Comment by nisshan-x** [comment]
I tried command with option `roslaunch depthai_examples stereo_nodelet.launch camera_model:=OAK-D-LITE` , but the result was the same...

**Comment by saching13** [comment]
I think stereo_nodelet is not configured for OAK-D-Lite with resolution. Will add it today mostly. 
cc: @daxoft  can add this to all the examples here ?

**Comment by daxoft** [comment]
Merged into main 
https://github.com/luxonis/depthai-ros-examples/pull/20 
https://github.com/luxonis/depthai-ros/pull/67
