### ISSUE TITLE
depthai_bridge/BridgePublisher::~BridgePublisher()  Bug?

### ISSUE THREAD

**Issue by tosa-no-onchan** [luxonis/depthai-ros#71]
stereo_nodelet.cpp terminates with error message.
I think, 
depthai_bridge/BridgePublisher::~BridgePublisher()  Bug?

Are try and catch codes needed?

https://github.com/luxonis/depthai-ros/blob/21baff8e923e7ea0df60a2138174e5d14d306fdd/depthai_bridge/include/depthai_bridge/BridgePublisher.hpp#L163-L167
----
template <class RosMsg, class SimMsg> 
BridgePublisher<RosMsg, SimMsg>::~BridgePublisher(){
  try{
    _readingThread.join();  
  }
  catch(_Unwind_RaiseException e){}
}

**Comment by themarpe** [comment]
@tosa-no-onchan thanks for reporting!
Do you have a specific scenario where/when this happens in that example?

@saching13 I think the following is required:
```
template <class RosMsg, class SimMsg>
BridgePublisher<RosMsg, SimMsg>::~BridgePublisher() {
    if(_readingThread.joinable()) _readingThread.join();
}
```

As if `startPublisherThread` isn't called, the above will throw

**Comment by saching13** [comment]
Yes. Sorry I missed that. Fixing it.

**Comment by saching13** [comment]
Fixed it.

**Comment by tosa-no-onchan** [comment]
Thank you,seaching13.

It worked!
Stereo_nodelet.launch become to terminate with no error.
