### ISSUE TITLE
problem while running ros2 launch depthai_examle yolov4_publisher_launch.py

### ISSUE THREAD

**Issue by Nicoladao** [luxonis/depthai-ros#87]
![image](https://user-images.githubusercontent.com/26049823/156537023-3e160159-d247-4e8a-9d72-5e38cfbbec0c.png)
Hi,
    When i run ros2 launch depthai_examle yolov4_publisher_launch.py, and it cannot continue.Do you know what problem with it ,how to fix?
Thank you!
ubuntu20.04 OAK-D-POE ROS2

**Comment by saching13** [comment]
Actually it is working for you. I have not added visualization for it. Start an Rviz or Rqt_image_view to see visualization. 
That said we still have to add plugins for our custom messages too.

**Comment by Nicoladao** [comment]
> Actually I think it is working for you. I have not added visualization for it. Start an Rviz or Rqt_image_view to see visualization. That said we still have to add plugins for our custom messages too.

Thanks, that's true. I can echo the topic.I thought there was a visualization.

And,if this package can use the function of getCvFrame() and getFrame()?

**Comment by Nicoladao** [comment]
> Actually I think it is working for you. I have not added visualization for it. Start an Rviz or Rqt_image_view to see visualization. That said we still have to add plugins for our custom messages too.

![image](https://user-images.githubusercontent.com/26049823/157227829-080e325d-aed5-48d0-9ff0-15af58a6fe30.png)
the error show like this.

It is foxy and I create my own ros-package to run the yolo-net.Should i set opencv in cmakelist.txt?

**Comment by saching13** [comment]
I think you need to add `depthai::opencv` as dependency here.
[here](https://github.com/luxonis/depthai-core#cmake) is more documentation on the same.

**Comment by Nicoladao** [comment]
> I think you need to add `depthai::opencv` as dependency here. And also make sure you have OpenCV installed so that those functions are built using that. [here](https://github.com/luxonis/depthai-core#cmake) is more documentation on the same.

Thanks very much.I forget to add depthai::opencv as dependency, it is works now!
very appreciated
