### ISSUE TITLE
Use ros2 and run examples but Oak-d indicates that the connection fails

### ISSUE THREAD

**Issue by sunil-gitcode** [luxonis/depthai-ros#89]
cmd :ros2 launch depthai_examples stereo.launch.py
<img width="590" alt="91df19a267007ed62f95ae0d9b06e50" src="https://user-images.githubusercontent.com/85002625/157617244-b58af68e-6098-48de-b655-0771cd366240.png">
<img width="659" alt="e52d9053ae247546b27d1b13309bc2b" src="https://user-images.githubusercontent.com/85002625/157617251-33855fe8-c89b-40f5-837d-12869ee0cdbb.png">

**Comment by saching13** [comment]
Hello,
Sorry fro the issue.

1. Can you check if the stereo works on depthai_demo.py ? 
2. Can you cross-check if the right DepthAI C++ library is installed.

**Comment by sunil-gitcode** [comment]
Run python3 depthai-demo.py but apparently it's fine so I don't know what the problem is  
<img width="527" alt="7863CF6A-93FF-47b2-B2B0-7D4C7F4A0B80" src="https://user-images.githubusercontent.com/85002625/157779275-68fc7219-653c-4af2-a953-9242a4ac3703.png">

**Comment by saching13** [comment]
In ros installation steps did you install the main branch ? And also when installing the dependencies was there any change ?

**Comment by sunil-gitcode** [comment]
I installed it according to the tutorial,command is sudo apt install ros-galactic-desktop
.Dependencies are installed automatically,I wonder what has changed about it.

**Comment by saching13** [comment]
Can you run the Installation dependencies [here](https://github.com/luxonis/depthai-ros#install-dependencies) followed by cleaning the WS and rebuilding the packages?

**Comment by sunil-gitcode** [comment]
<img width="354" alt="6210A26A-BBC5-4dd2-9C5D-4F42B8A85D85" src="https://user-images.githubusercontent.com/85002625/157782172-cd44ba8c-da9f-4393-b03c-0134c515baa0.png">


Follow the depth-ros tutorial ,i coclon build it and It say that the compilation succeeded,.Run to this step source devel/setup.bash,it  says no such file,so i put it into the ros2 project and compile it again.

**Comment by saching13** [comment]
`devel/setup.bash` is for ros 1. `install/setup.bash` is for ros2.

**Comment by sunil-gitcode** [comment]
Thank you for your help
1.It is depthai-ros project,It's just that the name is wrong.
2.depth-ros Dependencies are perfectly installed.
2. According to the tutorial, Dependency installation is based on install_dependencies.sh，Its compile and install prompts are successful.
3. Do I need to try all the steps again including ro2 installation

**Comment by saching13** [comment]
And you are still facing the issue ? 
3. No.

**Comment by sunil-gitcode** [comment]
yes,I still don't know what his problem is.I have to put the point cloud data into ROS2，It's an engineering project.

**Comment by saching13** [comment]
> put

Can you share the full logs on the terminal ?

**Comment by sunil-gitcode** [comment]
[log.txt](https://github.com/luxonis/depthai-ros/files/8228323/log.txt)
This is the log

**Comment by saching13** [comment]
Ok. In depthai_demo.py can you share the left camera image on the display ?

**Comment by saching13** [comment]
And logs from depthai demo too.

**Comment by sunil-gitcode** [comment]
<img width="614" alt="C09006DF-597E-48e6-A0DD-F8F9991CF489" src="https://user-images.githubusercontent.com/85002625/157787851-9a35a7e6-c879-49d1-8c77-9e4c62d0a05d.png">
Is that the choice

**Comment by saching13** [comment]
![image](https://user-images.githubusercontent.com/43363595/157788185-e7404472-966c-4af6-a68d-92d9f96c45d2.png)
No. Once the demo starts you have to change the camera where I have marked to left. And also share the logs printed in the terminal when running the demo

**Comment by sunil-gitcode** [comment]
<img width="640" alt="CE298814-CB24-4270-90AF-D4DB73AF3CF8" src="https://user-images.githubusercontent.com/85002625/157788750-b0a9753a-73c9-4b1c-9adb-9b0e71df7a45.png">
It doesn't seem to have that option

**Comment by saching13** [comment]
that means like Erik mentioned the connector might be disconnected or you have OAK-1. 
I think your connector might be disconnected.

**Comment by saching13** [comment]
Yes. Or we can get it replaced I think. Do you have an idea when it was purchased ?

**Comment by sunil-gitcode** [comment]
I bought it in December 21, I tried to repair it first to see.

**Comment by sunil-gitcode** [comment]
thanks you for your help, The problem was solved.
