### ISSUE TITLE
oak-d-lite with vins-gpu

### ISSUE THREAD

**Issue by sumzora** [luxonis/depthai-ros#92]
When I run roslaunch vins oak.launch according to this website (https://www.arducam.com/docs/opencv-ai-kit-oak/performing-location-with-visual-slam/), the error comes with **unused args [camera_name],for include ~<path>/luxonis/depthai-ros/depthai_bridge/launch/urdf.launch**
what's the camera name?
Thank you very much!

**Comment by saching13** [comment]
replace the `camera_name` with `tf_prefix`

**Comment by sumzora** [comment]
Oh, I still can not fix it. The specific error is following:
![微信图片_20220322170315](https://user-images.githubusercontent.com/74706383/159444912-93ce9f5e-b555-43ec-9c74-219b0f29bed7.jpg)
But my depthai-ros is installed well since I can run roslaunch depthai_examples stereo_node.launch and get pointcloud.

**Comment by Serafadam** [comment]
Hi, wanted to check in if you still have problems with that, the repo has been updated a little bit since March (and will be overhauled in near future), I'll close this issue for now since it's inactive for now but we can reopen it if you feel this still needs to be addressed.
