### ISSUE TITLE
ROS2 qos best-effort

### ISSUE THREAD

**Issue by gecastro** [luxonis/depthai-ros#94]
Hi,

I think that by default the publishers use the pocily 'reliable'. Is there a way to create a BridgePublisher using the qos reliability policy of best-effort?

**Comment by saching13** [comment]
Yes. We will be adding an option to change it. It's in the queue.

**Comment by hidmic** [comment]
Any updates on this @saching13 ?

**Comment by saching13** [comment]
Cc: @Serafadam

**Comment by Serafadam** [comment]
Thanks for notification, adding it to the next items in roadmap.
